#!/bin/bash

# Copyright (C) 2010 Red Hat, Inc.

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

# Uncomment for debugging.
#ECHO=echo

bucket=$1; shift
object=$1; shift
api_key=$1; shift
api_secret=$1; shift
cert_file=$1; shift
key_file=$1; shift
api_uid=$1; shift
ami_bkt=$1; shift
kernel=$1; shift
ramdisk=$1; shift

# TBD: figure out what to do about these paths.
export EC2_HOME=~/jdarcy/ec2-api-tools-1.3-53907
export PATH=$PATH:$EC2_HOME/bin
export JAVA_HOME=/usr

tmpdir=$(mktemp -d -p $PWD/$bucket)
trap "rm -rf $tmpdir" EXIT

bundle_args="--batch --arch x86_64 -c $cert_file -k $key_file -u $api_uid"
if [ "$kernel" != "_default_" ]; then
	bundle_args="$bundle_args --kernel $kernel"
fi
if [ "$ramdisk" != "_default_" ]; then
	bundle_args="$bundle_args --ramdisk $ramdisk"
fi
$ECHO ec2-bundle-image -i $bucket/$object -d $tmpdir $bundle_args
if [ $? != 0 ]; then
	echo "ERROR bundling_failed"
	echo ec2-bundle-image -i $bucket/$object -d $tmpdir $bundle_args
	exit 1
fi

upload_args="--batch --retry -b $ami_bkt -a $api_key -s $api_secret"
$ECHO ec2-upload-bundle -m $tmpdir/$object.manifest.xml $upload_args
if [ $? != 0 ]; then
	echo "ERROR uploading_failed"
	echo ec2-upload-bundle -m $tmpdir/$object.manifest.xml $upload_args
	exit 1
fi

register_args="-C $cert_file -K $key_file"
$ECHO ec2-register $register_args $ami_bkt/$object.manifest.xml -n $object
if [ $? != 0 ]; then
	echo "ERROR registration_failed"
	echo ec2-register $register_args $ami_bkt/$object.manifest.xml -n $object
	exit 1
fi
