/* A recursive-descent parser generated by peg 0.1.2 */

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#define YYRULECOUNT 24

#include <stdio.h>
#include <stdlib.h>
#include <time.h>
#include "query.h"

char *arg_buf;
int arg_off;
int arg_len;
value_t **cur_expr;

/* TBD: use separate function to parse dates differently */
value_t *
make_number (char *text)
{
	value_t *tmp = malloc(sizeof(*tmp));

	if (tmp) {
		tmp->type = T_NUMBER;
		tmp->as_num = strtoll(text,NULL,10);
	}

	return tmp;
}

value_t *
make_string (char *text, type_t t)
{
	value_t *tmp = malloc(sizeof(*tmp));

	if (tmp) {
		tmp->type = t;
		tmp->as_str = strdup(text);
	}

	return tmp;
}

value_t *
make_tree (type_t t, value_t *left, value_t *right)
{
	value_t *tmp = malloc(sizeof(*tmp));

	if (tmp) {
		tmp->type = t;
		tmp->as_tree.left = left;
		tmp->as_tree.right = right;
	}

	return tmp;
}

value_t *
make_comp (comp_t c, value_t *left, value_t *right)
{
	value_t *tmp = make_tree(T_COMP,left,right);

	if (tmp) {
		tmp->as_tree.op = c;
	}

	return tmp;
}

#if defined(UNIT_TEST)
struct { char *name; char *value; } hacked_obj_fields[] = {
	{ "a", "2" }, { "b", "7" }, { "c", "11" },
	{ NULL }
};

char *
unit_oget_func (void * notused, char *text)
{
	int i;

	for (i = 0; hacked_obj_fields[i].name; ++i) {
		if (!strcmp(hacked_obj_fields[i].name,text)) {
			return hacked_obj_fields[i].value;
		}
	}

	return NULL;
}
getter_t unit_oget = { unit_oget_func };

char *
unit_sget_func (void * notused, char *text)
{
	return "never";
}
getter_t unit_sget = { unit_sget_func };
#endif

char *
string_value (value_t *v, getter_t *oget, getter_t *sget)
{
	switch (v->type) {
	case T_STRING:
		return v->as_str;
	case T_OFIELD:
		return oget ? CALL_GETTER(oget,v->as_str) : "";
	case T_SFIELD:
		return sget ? CALL_GETTER(sget,v->as_str) : "";
	default:
		return NULL;
	}
}

int
is_ok_number (char *a_str)
{
	char	*p;

	if (!a_str) {
		return 0;
	}

	for (p = a_str; *p; ++p) {
		if (!isdigit(*p)) {
			return 0;
		}
	}

	return 1;
}

int
compare (value_t *left, comp_t op, value_t *right,
	 getter_t *oget, getter_t *sget)
{
	char	*lstr;
	char	*rstr;
	int	 lval;
	int	 rval;
	int	 num_ok = 1;

	lstr = string_value(left,oget,sget);
	rstr = string_value(right,oget,sget);

	if (left->type == T_NUMBER) {
		lval = left->as_num;
	}
	else if (lstr) {
		if (is_ok_number(lstr)) {
			lval = strtoll(lstr,NULL,0);
		}
		else {
			num_ok = 0;
		}
	}
	else {
		lval = eval(left,oget,sget);
		if (lval < 0) {
			return lval;
		}
	}

	if (right->type == T_NUMBER) {
		rval = right->as_num;
	}
	else if (rstr) {
		if (is_ok_number(rstr)) {
			rval = strtoll(rstr,NULL,0);
		}
		else {
			num_ok = 0;
		}
	}
	else {
		rval = eval(right,oget,sget);
		if (rval < 0) {
			return rval;
		}
	}

	if (!num_ok) {
		if (!lstr || !rstr) {
			return -1;
		}
		lval = strcmp(lstr,rstr);
		rval = 0;
	}

	switch (op) {
	case C_LESSTHAN:	return (lval < rval);
	case C_LESSOREQ:	return (lval <= rval);
	case C_EQUAL:		return (lval == rval);
	case C_DIFFERENT:	return (lval != rval);
	case C_GREATEROREQ:	return (lval >= rval);
	case C_GREATERTHAN:	return (lval > rval);
	default:
		return -1;
	}
}

void
_print_value (value_t *v, int level)
{
	if (!v) {
		printf("%*sNULL\n",level,"");
		return;
	}

	switch (v->type) {
	case T_NUMBER:
		printf("%*sNUMBER %lld\n",level,"",v->as_num);
		break;
	case T_STRING:
		printf("%*sSTRING %s\n",level,"",v->as_str);
		break;
	case T_OFIELD:
#if defined(UNIT_TEST)
		printf("%*sOBJECT FIELD %s (%s)\n",level,"",v->as_str,
			unit_oget_func(NULL,v->as_str));
#else
		printf("%*sOBJECT FIELD %s\n",level,"",v->as_str);
#endif
		break;
	case T_SFIELD:
#if defined(UNIT_TEST)
		printf("%*sSERVER FIELD %s (%s)\n",level,"",v->as_str,
			unit_sget_func(NULL,v->as_str));
#else
		printf("%*sSERVER FIELD %s\n",level,"",v->as_str);
#endif
		break;
	case T_COMP:
		printf("%*sCOMPARISON (%d)\n",level,"",v->as_num);
		_print_value(v->as_tree.left,level+2);
		_print_value(v->as_tree.right,level+2);
		break;
	case T_NOT:
		printf("%*sNOT\n",level,"");
		_print_value(v->as_tree.left,level+2);
		break;
	case T_AND:
		printf("%*sAND\n",level,"");
		_print_value(v->as_tree.left,level+2);
		_print_value(v->as_tree.right,level+2);
		break;
	case T_OR:
		printf("%*sOR\n",level,"");
		_print_value(v->as_tree.left,level+2);
		_print_value(v->as_tree.right,level+2);
		break;
	default:
		printf("%*sUNKNOWN %d\n",v->type,level,"");
	}
}

void
print_value (value_t *v)
{
	_print_value(v,0);
}

void
free_value (value_t *v)
{
	if (!v) {
		return;
	}

	switch (v->type) {
	case T_STRING:
	case T_OFIELD:
	case T_SFIELD:
		if (v->as_str) {
			free(v->as_str);
		}
		break;
	case T_COMP:
	case T_AND:
	case T_OR:
		free_value(v->as_tree.right);
		/* Fall through. */
	case T_NOT:
		free_value(v->as_tree.left);
		/* Fall through. */
	default:
		free(v);
	}
}

int
eval (value_t *v, getter_t *oget, getter_t *sget)
{
	int	res;

	switch (v->type) {
	case T_NUMBER:
		return v->as_num != 0;
	case T_STRING:
	case T_OFIELD:
	case T_SFIELD:
		return -1;
	case T_COMP:
		return compare(v->as_tree.left,(comp_t)v->as_tree.op,
			v->as_tree.right, oget, sget);
	case T_NOT:
		res = eval(v->as_tree.left,oget,sget);
		return (res >= 0) ? !res : res;
	case T_AND:
		res = eval(v->as_tree.left,oget,sget);
		if (res > 0) {
			res = eval(v->as_tree.right,oget,sget);
		}
		return res;
	case T_OR:
		res = eval(v->as_tree.left,oget,sget);
		if (res > 0) {
			return res;
		}
		return eval(v->as_tree.right,oget,sget);
	default:
		return -1;
	}
}

#define YY_INPUT(buf,result,max) {					  \
	result = (arg_off < arg_len) ? (*buf = arg_buf[arg_off++], 1)	  \
		: (arg_off == arg_len) ? (*buf = '\n', ++arg_off, 1) : 0; \
}

#define YYSTYPE value_t *

#ifndef YY_VARIABLE
#define YY_VARIABLE(T)	static T
#endif
#ifndef YY_LOCAL
#define YY_LOCAL(T)	static T
#endif
#ifndef YY_ACTION
#define YY_ACTION(T)	static T
#endif
#ifndef YY_RULE
#define YY_RULE(T)	static T
#endif
#ifndef YY_PARSE
#define YY_PARSE(T)	T
#endif
#ifndef YYPARSE
#define YYPARSE		yyparse
#endif
#ifndef YYPARSEFROM
#define YYPARSEFROM	yyparsefrom
#endif
#ifndef YY_INPUT
#define YY_INPUT(buf, result, max_size)			\
  {							\
    int yyc= getchar();					\
    result= (EOF == yyc) ? 0 : (*(buf)= yyc, 1);	\
    yyprintf((stderr, "<%c>", yyc));			\
  }
#endif
#ifndef YY_BEGIN
#define YY_BEGIN	( yybegin= yypos, 1)
#endif
#ifndef YY_END
#define YY_END		( yyend= yypos, 1)
#endif
#ifdef YY_DEBUG
# define yyprintf(args)	fprintf args
#else
# define yyprintf(args)
#endif
#ifndef YYSTYPE
#define YYSTYPE	int
#endif

#ifndef YY_PART

typedef void (*yyaction)(char *yytext, int yyleng);
typedef struct _yythunk { int begin, end;  yyaction  action;  struct _yythunk *next; } yythunk;

YY_VARIABLE(char *   ) yybuf= 0;
YY_VARIABLE(int	     ) yybuflen= 0;
YY_VARIABLE(int	     ) yypos= 0;
YY_VARIABLE(int	     ) yylimit= 0;
YY_VARIABLE(char *   ) yytext= 0;
YY_VARIABLE(int	     ) yytextlen= 0;
YY_VARIABLE(int	     ) yybegin= 0;
YY_VARIABLE(int	     ) yyend= 0;
YY_VARIABLE(int	     ) yytextmax= 0;
YY_VARIABLE(yythunk *) yythunks= 0;
YY_VARIABLE(int	     ) yythunkslen= 0;
YY_VARIABLE(int      ) yythunkpos= 0;
YY_VARIABLE(YYSTYPE  ) yy;
YY_VARIABLE(YYSTYPE *) yyval= 0;
YY_VARIABLE(YYSTYPE *) yyvals= 0;
YY_VARIABLE(int      ) yyvalslen= 0;

YY_LOCAL(int) yyrefill(void)
{
  int yyn;
  while (yybuflen - yypos < 512)
    {
      yybuflen *= 2;
      yybuf= realloc(yybuf, yybuflen);
    }
  YY_INPUT((yybuf + yypos), yyn, (yybuflen - yypos));
  if (!yyn) return 0;
  yylimit += yyn;
  return 1;
}

YY_LOCAL(int) yymatchDot(void)
{
  if (yypos >= yylimit && !yyrefill()) return 0;
  ++yypos;
  return 1;
}

YY_LOCAL(int) yymatchChar(int c)
{
  if (yypos >= yylimit && !yyrefill()) return 0;
  if (yybuf[yypos] == c)
    {
      ++yypos;
      yyprintf((stderr, "  ok   yymatchChar(%c) @ %s\n", c, yybuf+yypos));
      return 1;
    }
  yyprintf((stderr, "  fail yymatchChar(%c) @ %s\n", c, yybuf+yypos));
  return 0;
}

YY_LOCAL(int) yymatchString(char *s)
{
  int yysav= yypos;
  while (*s)
    {
      if (yypos >= yylimit && !yyrefill()) return 0;
      if (yybuf[yypos] != *s)
        {
          yypos= yysav;
          return 0;
        }
      ++s;
      ++yypos;
    }
  return 1;
}

YY_LOCAL(int) yymatchClass(unsigned char *bits)
{
  int c;
  if (yypos >= yylimit && !yyrefill()) return 0;
  c= yybuf[yypos];
  if (bits[c >> 3] & (1 << (c & 7)))
    {
      ++yypos;
      yyprintf((stderr, "  ok   yymatchClass @ %s\n", yybuf+yypos));
      return 1;
    }
  yyprintf((stderr, "  fail yymatchClass @ %s\n", yybuf+yypos));
  return 0;
}

YY_LOCAL(void) yyDo(yyaction action, int begin, int end)
{
  while (yythunkpos >= yythunkslen)
    {
      yythunkslen *= 2;
      yythunks= realloc(yythunks, sizeof(yythunk) * yythunkslen);
    }
  yythunks[yythunkpos].begin=  begin;
  yythunks[yythunkpos].end=    end;
  yythunks[yythunkpos].action= action;
  ++yythunkpos;
}

YY_LOCAL(int) yyText(int begin, int end)
{
  int yyleng= end - begin;
  if (yyleng <= 0)
    yyleng= 0;
  else
    {
      while (yytextlen < (yyleng - 1))
	{
	  yytextlen *= 2;
	  yytext= realloc(yytext, yytextlen);
	}
      memcpy(yytext, yybuf + begin, yyleng);
    }
  yytext[yyleng]= '\0';
  return yyleng;
}

YY_LOCAL(void) yyDone(void)
{
  int pos;
  for (pos= 0;  pos < yythunkpos;  ++pos)
    {
      yythunk *thunk= &yythunks[pos];
      int yyleng= thunk->end ? yyText(thunk->begin, thunk->end) : thunk->begin;
      yyprintf((stderr, "DO [%d] %p %s\n", pos, thunk->action, yytext));
      thunk->action(yytext, yyleng);
    }
  yythunkpos= 0;
}

YY_LOCAL(void) yyCommit()
{
  if ((yylimit -= yypos))
    {
      memmove(yybuf, yybuf + yypos, yylimit);
    }
  yybegin -= yypos;
  yyend -= yypos;
  yypos= yythunkpos= 0;
}

YY_LOCAL(int) yyAccept(int tp0)
{
  if (tp0)
    {
      fprintf(stderr, "accept denied at %d\n", tp0);
      return 0;
    }
  else
    {
      yyDone();
      yyCommit();
    }
  return 1;
}

YY_LOCAL(void) yyPush(char *text, int count)	{ yyval += count; }
YY_LOCAL(void) yyPop(char *text, int count)	{ yyval -= count; }
YY_LOCAL(void) yySet(char *text, int count)	{ yyval[count]= yy; }

#endif /* YY_PART */

#define	YYACCEPT	yyAccept(yythunkpos0)

YY_RULE(int) yy_CLOSE(); /* 24 */
YY_RULE(int) yy_OPEN(); /* 23 */
YY_RULE(int) yy_WAFFLE(); /* 22 */
YY_RULE(int) yy_ID(); /* 21 */
YY_RULE(int) yy_DOLLAR(); /* 20 */
YY_RULE(int) yy_TIME(); /* 19 */
YY_RULE(int) yy_STRING(); /* 18 */
YY_RULE(int) yy_NUMBER(); /* 17 */
YY_RULE(int) yy_ParenExpr(); /* 16 */
YY_RULE(int) yy_Field(); /* 15 */
YY_RULE(int) yy_Literal(); /* 14 */
YY_RULE(int) yy_Atom(); /* 13 */
YY_RULE(int) yy_GREATER(); /* 12 */
YY_RULE(int) yy_NOT(); /* 11 */
YY_RULE(int) yy_EQUAL(); /* 10 */
YY_RULE(int) yy_LESS(); /* 9 */
YY_RULE(int) yy_Unary(); /* 8 */
YY_RULE(int) yy_OR(); /* 7 */
YY_RULE(int) yy_AND(); /* 6 */
YY_RULE(int) yy_CompExpr(); /* 5 */
YY_RULE(int) yy_EOL(); /* 4 */
YY_RULE(int) yy_BoolExpr(); /* 3 */
YY_RULE(int) yy__(); /* 2 */
YY_RULE(int) yy_Stmt(); /* 1 */

YY_ACTION(void) yy_1_ID(char *yytext, int yyleng)
{
  yyprintf((stderr, "do yy_1_ID\n"));
   yy = (YYSTYPE)yytext; ;
}
YY_ACTION(void) yy_1_TIME(char *yytext, int yyleng)
{
  yyprintf((stderr, "do yy_1_TIME\n"));
   yy = make_number(yytext); ;
}
YY_ACTION(void) yy_1_STRING(char *yytext, int yyleng)
{
  yyprintf((stderr, "do yy_1_STRING\n"));
   yy = make_string(yytext,T_STRING); ;
}
YY_ACTION(void) yy_1_NUMBER(char *yytext, int yyleng)
{
  yyprintf((stderr, "do yy_1_NUMBER\n"));
   yy= make_number(yytext); ;
}
YY_ACTION(void) yy_1_ParenExpr(char *yytext, int yyleng)
{
#define v yyval[-1]
  yyprintf((stderr, "do yy_1_ParenExpr\n"));
   yy = v; ;
#undef v
}
YY_ACTION(void) yy_2_Field(char *yytext, int yyleng)
{
#define i yyval[-1]
  yyprintf((stderr, "do yy_2_Field\n"));
   yy = make_string((char *)yy,T_SFIELD); ;
#undef i
}
YY_ACTION(void) yy_1_Field(char *yytext, int yyleng)
{
#define i yyval[-1]
  yyprintf((stderr, "do yy_1_Field\n"));
   yy = make_string((char *)yy,T_OFIELD); ;
#undef i
}
YY_ACTION(void) yy_2_Unary(char *yytext, int yyleng)
{
#define e yyval[-1]
  yyprintf((stderr, "do yy_2_Unary\n"));
   yy = make_tree(T_NOT,e,NULL); ;
#undef e
}
YY_ACTION(void) yy_1_Unary(char *yytext, int yyleng)
{
#define e yyval[-1]
  yyprintf((stderr, "do yy_1_Unary\n"));
   yy = make_tree(T_NOT,e,NULL); ;
#undef e
}
YY_ACTION(void) yy_6_CompExpr(char *yytext, int yyleng)
{
#define r yyval[-1]
#define l yyval[-2]
  yyprintf((stderr, "do yy_6_CompExpr\n"));
   yy = make_comp(C_GREATERTHAN,l,r); ;
#undef r
#undef l
}
YY_ACTION(void) yy_5_CompExpr(char *yytext, int yyleng)
{
#define r yyval[-1]
#define l yyval[-2]
  yyprintf((stderr, "do yy_5_CompExpr\n"));
   yy = make_comp(C_GREATEROREQ,l,r); ;
#undef r
#undef l
}
YY_ACTION(void) yy_4_CompExpr(char *yytext, int yyleng)
{
#define r yyval[-1]
#define l yyval[-2]
  yyprintf((stderr, "do yy_4_CompExpr\n"));
   yy = make_comp(C_DIFFERENT,l,r); ;
#undef r
#undef l
}
YY_ACTION(void) yy_3_CompExpr(char *yytext, int yyleng)
{
#define r yyval[-1]
#define l yyval[-2]
  yyprintf((stderr, "do yy_3_CompExpr\n"));
   yy = make_comp(C_EQUAL,l,r); ;
#undef r
#undef l
}
YY_ACTION(void) yy_2_CompExpr(char *yytext, int yyleng)
{
#define r yyval[-1]
#define l yyval[-2]
  yyprintf((stderr, "do yy_2_CompExpr\n"));
   yy = make_comp(C_LESSOREQ,l,r); ;
#undef r
#undef l
}
YY_ACTION(void) yy_1_CompExpr(char *yytext, int yyleng)
{
#define r yyval[-1]
#define l yyval[-2]
  yyprintf((stderr, "do yy_1_CompExpr\n"));
   yy = make_comp(C_LESSTHAN,l,r); ;
#undef r
#undef l
}
YY_ACTION(void) yy_2_BoolExpr(char *yytext, int yyleng)
{
#define r yyval[-1]
#define l yyval[-2]
  yyprintf((stderr, "do yy_2_BoolExpr\n"));
   yy = make_tree(T_OR,l,r); ;
#undef r
#undef l
}
YY_ACTION(void) yy_1_BoolExpr(char *yytext, int yyleng)
{
#define r yyval[-1]
#define l yyval[-2]
  yyprintf((stderr, "do yy_1_BoolExpr\n"));
   yy = make_tree(T_AND,l,r); ;
#undef r
#undef l
}
YY_ACTION(void) yy_1_Stmt(char *yytext, int yyleng)
{
  yyprintf((stderr, "do yy_1_Stmt\n"));
   *cur_expr = yy; ;
}

YY_RULE(int) yy_CLOSE()
{  int yypos0= yypos, yythunkpos0= yythunkpos;
  yyprintf((stderr, "%s\n", "CLOSE"));  if (!yymatchChar(')')) goto l1;
  yyprintf((stderr, "  ok   %s @ %s\n", "CLOSE", yybuf+yypos));
  return 1;
  l1:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "CLOSE", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy_OPEN()
{  int yypos0= yypos, yythunkpos0= yythunkpos;
  yyprintf((stderr, "%s\n", "OPEN"));  if (!yymatchChar('(')) goto l2;
  yyprintf((stderr, "  ok   %s @ %s\n", "OPEN", yybuf+yypos));
  return 1;
  l2:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "OPEN", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy_WAFFLE()
{  int yypos0= yypos, yythunkpos0= yythunkpos;
  yyprintf((stderr, "%s\n", "WAFFLE"));  if (!yymatchChar('#')) goto l3;
  yyprintf((stderr, "  ok   %s @ %s\n", "WAFFLE", yybuf+yypos));
  return 1;
  l3:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "WAFFLE", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy_ID()
{  int yypos0= yypos, yythunkpos0= yythunkpos;
  yyprintf((stderr, "%s\n", "ID"));  yyText(yybegin, yyend);  if (!(YY_BEGIN)) goto l4;  if (!yymatchClass((unsigned char *)"\000\000\000\000\000\000\000\000\000\000\000\200\376\377\377\007\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000")) goto l4;
  l5:;	
  {  int yypos6= yypos, yythunkpos6= yythunkpos;  if (!yymatchClass((unsigned char *)"\000\000\000\000\000\000\000\000\000\000\000\200\376\377\377\007\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000")) goto l6;  goto l5;
  l6:;	  yypos= yypos6; yythunkpos= yythunkpos6;
  }  yyText(yybegin, yyend);  if (!(YY_END)) goto l4;  yyDo(yy_1_ID, yybegin, yyend);
  yyprintf((stderr, "  ok   %s @ %s\n", "ID", yybuf+yypos));
  return 1;
  l4:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "ID", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy_DOLLAR()
{  int yypos0= yypos, yythunkpos0= yythunkpos;
  yyprintf((stderr, "%s\n", "DOLLAR"));  if (!yymatchChar('$')) goto l7;
  yyprintf((stderr, "  ok   %s @ %s\n", "DOLLAR", yybuf+yypos));
  return 1;
  l7:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "DOLLAR", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy_TIME()
{  int yypos0= yypos, yythunkpos0= yythunkpos;
  yyprintf((stderr, "%s\n", "TIME"));  if (!yymatchChar('~')) goto l8;  yyText(yybegin, yyend);  if (!(YY_BEGIN)) goto l8;
  l9:;	
  {  int yypos10= yypos, yythunkpos10= yythunkpos;  if (!yymatchClass((unsigned char *)"\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\277\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377")) goto l10;  goto l9;
  l10:;	  yypos= yypos10; yythunkpos= yythunkpos10;
  }  yyText(yybegin, yyend);  if (!(YY_END)) goto l8;  if (!yymatchChar('~')) goto l8;  yyDo(yy_1_TIME, yybegin, yyend);
  yyprintf((stderr, "  ok   %s @ %s\n", "TIME", yybuf+yypos));
  return 1;
  l8:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "TIME", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy_STRING()
{  int yypos0= yypos, yythunkpos0= yythunkpos;
  yyprintf((stderr, "%s\n", "STRING"));  if (!yymatchChar('"')) goto l11;  yyText(yybegin, yyend);  if (!(YY_BEGIN)) goto l11;
  l12:;	
  {  int yypos13= yypos, yythunkpos13= yythunkpos;  if (!yymatchClass((unsigned char *)"\377\377\377\377\373\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377")) goto l13;  goto l12;
  l13:;	  yypos= yypos13; yythunkpos= yythunkpos13;
  }  yyText(yybegin, yyend);  if (!(YY_END)) goto l11;  if (!yymatchChar('"')) goto l11;  yyDo(yy_1_STRING, yybegin, yyend);
  yyprintf((stderr, "  ok   %s @ %s\n", "STRING", yybuf+yypos));
  return 1;
  l11:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "STRING", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy_NUMBER()
{  int yypos0= yypos, yythunkpos0= yythunkpos;
  yyprintf((stderr, "%s\n", "NUMBER"));  yyText(yybegin, yyend);  if (!(YY_BEGIN)) goto l14;  if (!yymatchClass((unsigned char *)"\000\000\000\000\000\000\377\003\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000")) goto l14;
  l15:;	
  {  int yypos16= yypos, yythunkpos16= yythunkpos;  if (!yymatchClass((unsigned char *)"\000\000\000\000\000\000\377\003\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000")) goto l16;  goto l15;
  l16:;	  yypos= yypos16; yythunkpos= yythunkpos16;
  }  yyText(yybegin, yyend);  if (!(YY_END)) goto l14;  yyDo(yy_1_NUMBER, yybegin, yyend);
  yyprintf((stderr, "  ok   %s @ %s\n", "NUMBER", yybuf+yypos));
  return 1;
  l14:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "NUMBER", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy_ParenExpr()
{  int yypos0= yypos, yythunkpos0= yythunkpos;  yyDo(yyPush, 1, 0);
  yyprintf((stderr, "%s\n", "ParenExpr"));  if (!yy_OPEN()) goto l17;  if (!yy_BoolExpr()) goto l17;  yyDo(yySet, -1, 0);  if (!yy_CLOSE()) goto l17;  if (!yy__()) goto l17;  yyDo(yy_1_ParenExpr, yybegin, yyend);
  yyprintf((stderr, "  ok   %s @ %s\n", "ParenExpr", yybuf+yypos));  yyDo(yyPop, 1, 0);
  return 1;
  l17:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "ParenExpr", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy_Field()
{  int yypos0= yypos, yythunkpos0= yythunkpos;  yyDo(yyPush, 1, 0);
  yyprintf((stderr, "%s\n", "Field"));
  {  int yypos19= yypos, yythunkpos19= yythunkpos;  if (!yy_DOLLAR()) goto l20;  if (!yy_ID()) goto l20;  yyDo(yySet, -1, 0);  yyDo(yy_1_Field, yybegin, yyend);  goto l19;
  l20:;	  yypos= yypos19; yythunkpos= yythunkpos19;  if (!yy_WAFFLE()) goto l18;  if (!yy_ID()) goto l18;  yyDo(yySet, -1, 0);  yyDo(yy_2_Field, yybegin, yyend);
  }
  l19:;	
  yyprintf((stderr, "  ok   %s @ %s\n", "Field", yybuf+yypos));  yyDo(yyPop, 1, 0);
  return 1;
  l18:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "Field", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy_Literal()
{  int yypos0= yypos, yythunkpos0= yythunkpos;
  yyprintf((stderr, "%s\n", "Literal"));
  {  int yypos22= yypos, yythunkpos22= yythunkpos;  if (!yy_NUMBER()) goto l23;  goto l22;
  l23:;	  yypos= yypos22; yythunkpos= yythunkpos22;  if (!yy_STRING()) goto l24;  goto l22;
  l24:;	  yypos= yypos22; yythunkpos= yythunkpos22;  if (!yy_TIME()) goto l21;
  }
  l22:;	
  yyprintf((stderr, "  ok   %s @ %s\n", "Literal", yybuf+yypos));
  return 1;
  l21:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "Literal", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy_Atom()
{  int yypos0= yypos, yythunkpos0= yythunkpos;
  yyprintf((stderr, "%s\n", "Atom"));
  {  int yypos26= yypos, yythunkpos26= yythunkpos;  if (!yy_Literal()) goto l27;  goto l26;
  l27:;	  yypos= yypos26; yythunkpos= yythunkpos26;  if (!yy_Field()) goto l28;  goto l26;
  l28:;	  yypos= yypos26; yythunkpos= yythunkpos26;  if (!yy_ParenExpr()) goto l25;
  }
  l26:;	  if (!yy__()) goto l25;
  yyprintf((stderr, "  ok   %s @ %s\n", "Atom", yybuf+yypos));
  return 1;
  l25:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "Atom", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy_GREATER()
{  int yypos0= yypos, yythunkpos0= yythunkpos;
  yyprintf((stderr, "%s\n", "GREATER"));  if (!yymatchChar('>')) goto l29;
  yyprintf((stderr, "  ok   %s @ %s\n", "GREATER", yybuf+yypos));
  return 1;
  l29:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "GREATER", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy_NOT()
{  int yypos0= yypos, yythunkpos0= yythunkpos;
  yyprintf((stderr, "%s\n", "NOT"));  if (!yymatchChar('!')) goto l30;
  yyprintf((stderr, "  ok   %s @ %s\n", "NOT", yybuf+yypos));
  return 1;
  l30:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "NOT", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy_EQUAL()
{  int yypos0= yypos, yythunkpos0= yythunkpos;
  yyprintf((stderr, "%s\n", "EQUAL"));  if (!yymatchChar('=')) goto l31;
  yyprintf((stderr, "  ok   %s @ %s\n", "EQUAL", yybuf+yypos));
  return 1;
  l31:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "EQUAL", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy_LESS()
{  int yypos0= yypos, yythunkpos0= yythunkpos;
  yyprintf((stderr, "%s\n", "LESS"));  if (!yymatchChar('<')) goto l32;
  yyprintf((stderr, "  ok   %s @ %s\n", "LESS", yybuf+yypos));
  return 1;
  l32:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "LESS", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy_Unary()
{  int yypos0= yypos, yythunkpos0= yythunkpos;  yyDo(yyPush, 1, 0);
  yyprintf((stderr, "%s\n", "Unary"));
  {  int yypos34= yypos, yythunkpos34= yythunkpos;  if (!yy_Atom()) goto l35;  goto l34;
  l35:;	  yypos= yypos34; yythunkpos= yythunkpos34;  if (!yy_NOT()) goto l36;  if (!yy__()) goto l36;  if (!yy_Atom()) goto l36;  yyDo(yySet, -1, 0);  if (!yy__()) goto l36;  yyDo(yy_1_Unary, yybegin, yyend);  goto l34;
  l36:;	  yypos= yypos34; yythunkpos= yythunkpos34;  if (!yy_NOT()) goto l33;  if (!yy__()) goto l33;  if (!yy_Unary()) goto l33;  yyDo(yySet, -1, 0);  if (!yy__()) goto l33;  yyDo(yy_2_Unary, yybegin, yyend);
  }
  l34:;	
  yyprintf((stderr, "  ok   %s @ %s\n", "Unary", yybuf+yypos));  yyDo(yyPop, 1, 0);
  return 1;
  l33:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "Unary", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy_OR()
{  int yypos0= yypos, yythunkpos0= yythunkpos;
  yyprintf((stderr, "%s\n", "OR"));  if (!yymatchString("||")) goto l37;
  yyprintf((stderr, "  ok   %s @ %s\n", "OR", yybuf+yypos));
  return 1;
  l37:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "OR", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy_AND()
{  int yypos0= yypos, yythunkpos0= yythunkpos;
  yyprintf((stderr, "%s\n", "AND"));  if (!yymatchString("&&")) goto l38;
  yyprintf((stderr, "  ok   %s @ %s\n", "AND", yybuf+yypos));
  return 1;
  l38:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "AND", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy_CompExpr()
{  int yypos0= yypos, yythunkpos0= yythunkpos;  yyDo(yyPush, 2, 0);
  yyprintf((stderr, "%s\n", "CompExpr"));  if (!yy_Unary()) goto l39;  yyDo(yySet, -2, 0);
  {  int yypos40= yypos, yythunkpos40= yythunkpos;
  {  int yypos42= yypos, yythunkpos42= yythunkpos;  if (!yy_LESS()) goto l43;  if (!yy__()) goto l43;  if (!yy_Unary()) goto l43;  yyDo(yySet, -1, 0);  yyDo(yy_1_CompExpr, yybegin, yyend);  goto l42;
  l43:;	  yypos= yypos42; yythunkpos= yythunkpos42;  if (!yy_LESS()) goto l44;  if (!yy_EQUAL()) goto l44;  if (!yy__()) goto l44;  if (!yy_Unary()) goto l44;  yyDo(yySet, -1, 0);  yyDo(yy_2_CompExpr, yybegin, yyend);  goto l42;
  l44:;	  yypos= yypos42; yythunkpos= yythunkpos42;  if (!yy_EQUAL()) goto l45;  if (!yy_EQUAL()) goto l45;  if (!yy__()) goto l45;  if (!yy_Unary()) goto l45;  yyDo(yySet, -1, 0);  yyDo(yy_3_CompExpr, yybegin, yyend);  goto l42;
  l45:;	  yypos= yypos42; yythunkpos= yythunkpos42;  if (!yy_NOT()) goto l46;  if (!yy_EQUAL()) goto l46;  if (!yy__()) goto l46;  if (!yy_Unary()) goto l46;  yyDo(yySet, -1, 0);  yyDo(yy_4_CompExpr, yybegin, yyend);  goto l42;
  l46:;	  yypos= yypos42; yythunkpos= yythunkpos42;  if (!yy_GREATER()) goto l47;  if (!yy_EQUAL()) goto l47;  if (!yy__()) goto l47;  if (!yy_Unary()) goto l47;  yyDo(yySet, -1, 0);  yyDo(yy_5_CompExpr, yybegin, yyend);  goto l42;
  l47:;	  yypos= yypos42; yythunkpos= yythunkpos42;  if (!yy_GREATER()) goto l40;  if (!yy__()) goto l40;  if (!yy_Unary()) goto l40;  yyDo(yySet, -1, 0);  yyDo(yy_6_CompExpr, yybegin, yyend);
  }
  l42:;	  goto l41;
  l40:;	  yypos= yypos40; yythunkpos= yythunkpos40;
  }
  l41:;	  if (!yy__()) goto l39;
  yyprintf((stderr, "  ok   %s @ %s\n", "CompExpr", yybuf+yypos));  yyDo(yyPop, 2, 0);
  return 1;
  l39:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "CompExpr", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy_EOL()
{  int yypos0= yypos, yythunkpos0= yythunkpos;
  yyprintf((stderr, "%s\n", "EOL"));
  {  int yypos49= yypos, yythunkpos49= yythunkpos;  if (!yymatchChar('\n')) goto l50;  goto l49;
  l50:;	  yypos= yypos49; yythunkpos= yythunkpos49;  if (!yymatchString("\r\n")) goto l51;  goto l49;
  l51:;	  yypos= yypos49; yythunkpos= yythunkpos49;  if (!yymatchChar('\r')) goto l52;  goto l49;
  l52:;	  yypos= yypos49; yythunkpos= yythunkpos49;  if (!yymatchChar(';')) goto l48;
  }
  l49:;	
  yyprintf((stderr, "  ok   %s @ %s\n", "EOL", yybuf+yypos));
  return 1;
  l48:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "EOL", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy_BoolExpr()
{  int yypos0= yypos, yythunkpos0= yythunkpos;  yyDo(yyPush, 2, 0);
  yyprintf((stderr, "%s\n", "BoolExpr"));  if (!yy_CompExpr()) goto l53;  yyDo(yySet, -2, 0);
  l54:;	
  {  int yypos55= yypos, yythunkpos55= yythunkpos;
  {  int yypos56= yypos, yythunkpos56= yythunkpos;  if (!yy__()) goto l57;  if (!yy_AND()) goto l57;  if (!yy__()) goto l57;  if (!yy_CompExpr()) goto l57;  yyDo(yySet, -1, 0);  yyDo(yy_1_BoolExpr, yybegin, yyend);  goto l56;
  l57:;	  yypos= yypos56; yythunkpos= yythunkpos56;  if (!yy__()) goto l55;  if (!yy_OR()) goto l55;  if (!yy__()) goto l55;  if (!yy_CompExpr()) goto l55;  yyDo(yySet, -1, 0);  yyDo(yy_2_BoolExpr, yybegin, yyend);
  }
  l56:;	  goto l54;
  l55:;	  yypos= yypos55; yythunkpos= yythunkpos55;
  }  if (!yy__()) goto l53;
  yyprintf((stderr, "  ok   %s @ %s\n", "BoolExpr", yybuf+yypos));  yyDo(yyPop, 2, 0);
  return 1;
  l53:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "BoolExpr", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy__()
{
  yyprintf((stderr, "%s\n", "_"));
  l59:;	
  {  int yypos60= yypos, yythunkpos60= yythunkpos;  if (!yymatchClass((unsigned char *)"\000\002\000\000\001\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000")) goto l60;  goto l59;
  l60:;	  yypos= yypos60; yythunkpos= yythunkpos60;
  }
  yyprintf((stderr, "  ok   %s @ %s\n", "_", yybuf+yypos));
  return 1;
}
YY_RULE(int) yy_Stmt()
{  int yypos0= yypos, yythunkpos0= yythunkpos;
  yyprintf((stderr, "%s\n", "Stmt"));
  {  int yypos62= yypos, yythunkpos62= yythunkpos;  if (!yy__()) goto l63;  if (!yy_BoolExpr()) goto l63;  if (!yy_EOL()) goto l63;  yyDo(yy_1_Stmt, yybegin, yyend);  goto l62;
  l63:;	  yypos= yypos62; yythunkpos= yythunkpos62;
  l64:;	
  {  int yypos65= yypos, yythunkpos65= yythunkpos;
  {  int yypos66= yypos, yythunkpos66= yythunkpos;  if (!yy_EOL()) goto l66;  goto l65;
  l66:;	  yypos= yypos66; yythunkpos= yythunkpos66;
  }  if (!yymatchDot()) goto l65;  goto l64;
  l65:;	  yypos= yypos65; yythunkpos= yythunkpos65;
  }  if (!yy_EOL()) goto l61;
  }
  l62:;	
  yyprintf((stderr, "  ok   %s @ %s\n", "Stmt", yybuf+yypos));
  return 1;
  l61:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "Stmt", yybuf+yypos));
  return 0;
}

#ifndef YY_PART

typedef int (*yyrule)();

YY_PARSE(int) YYPARSEFROM(yyrule yystart)
{
  int yyok;
  if (!yybuflen)
    {
      yybuflen= 1024;
      yybuf= malloc(yybuflen);
      yytextlen= 1024;
      yytext= malloc(yytextlen);
      yythunkslen= 32;
      yythunks= malloc(sizeof(yythunk) * yythunkslen);
      yyvalslen= 32;
      yyvals= malloc(sizeof(YYSTYPE) * yyvalslen);
      yybegin= yyend= yypos= yylimit= yythunkpos= 0;
    }
  yybegin= yyend= yypos;
  yythunkpos= 0;
  yyval= yyvals;
  yyok= yystart();
  if (yyok) yyDone();
  yyCommit();
  return yyok;
  (void)yyrefill;
  (void)yymatchDot;
  (void)yymatchChar;
  (void)yymatchString;
  (void)yymatchClass;
  (void)yyDo;
  (void)yyText;
  (void)yyDone;
  (void)yyCommit;
  (void)yyAccept;
  (void)yyPush;
  (void)yyPop;
  (void)yySet;
  (void)yytextmax;
}

YY_PARSE(int) YYPARSE(void)
{
  return YYPARSEFROM(yy_Stmt);
}

#endif


value_t *
parse (char *text)
{
	value_t *expr = NULL;

	arg_buf = text;
	arg_len = strlen(text);
	arg_off = 0;
	cur_expr = &expr;

	while (yyparse()) {
	}

	return expr;
}

#if defined(UNIT_TEST)
int
main (int argc, char **argv)
{
	int	i;
	value_t *expr;

	for (i = 1; i < argc; ++i) {
		expr = parse(argv[i]);
		if (expr) {
			print_value(expr);
			printf("= %d\n",eval(expr,&unit_oget,&unit_sget));
		}
		else {
			printf("could not parse '%s'\n",argv[i]);
		}
	}

	return 0;
}
#endif

