#!/bin/sh
# exercise the parser

. "${srcdir=.}/init.sh"; path_prepend_ .

cat <<\EOF > f.exp || framework_failure_
AND
  COMPARISON
    SERVER FIELD a (never)
    STRING fubar
  NOT
    COMPARISON
      LINK
        LINK
          OBJECT FIELD b (7)
          DEST FIELD c
        DEST FIELD d
      NUMBER 3
d= 0
EOF

parser-test '#a=="fubar"&&!($b.c.d<3)' > features 2> err || fail=1
compare features f.exp || fail=1
compare /dev/null err || fail=1

parser-test '#a == "fubar" && ! ( $b.c.d < 3)' > white-space 2> err || fail=1
compare white-space f.exp || fail=1
compare /dev/null err || fail=1

parser-test '$ a' > a.out 2>&1 || fail=1
printf "OBJECT FIELD a (2)\ns= 2\n" > a.exp
compare a.out a.exp || fail=1

parser-test '$.a' > e1.out 2>&1; test $? = 1 || fail=1
printf "could not parse '$.a'\n" > e1.exp
compare e1.exp e1.out || fail=1

parser-test '1 = = 1' > e2.out 2>&1; test $? = 1 || fail=1
printf "could not parse '1 = = 1'\n" > e2.exp
compare e2.exp e2.out || fail=1

Exit $fail
